function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  stairs x
%  Y1:  stairs y

%  Auto-generated by MATLAB on 27-Jan-2020 09:12:57

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.113333333333334 0.0943342036553525 0.775000000000001 0.811428571428572]);
hold(axes1,'on');

% Create stairs
stairs(X1,Y1,'MarkerFaceColor',[1 1 0],...
    'MarkerEdgeColor',[1 0.843137264251709 0],...
    'MarkerSize',25,...
    'Marker','diamond',...
    'LineWidth',6,...
    'Color',[0 1 0]);

box(axes1,'on');
